# Generated by Django 5.2.15 on 2026-06-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_album_status_alter_track_status'),
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='playlisttrack',
            index=models.Index(fields=['playlist', 'order'], name='playlists_p_playlis_c81fae_idx'),
        ),
        migrations.AddConstraint(
            model_name='playlisttrack',
            constraint=models.UniqueConstraint(fields=('playlist', 'track'), name='unique_playlist_track'),
        ),
    ]
