# Generated by Django 6.0.6 on 2026-06-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_playlisttrack_playlists_p_playlis_c81fae_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['-created_at'], 'verbose_name': 'پلی لیست', 'verbose_name_plural': 'پلی لیست ها'},
        ),
        migrations.AlterModelOptions(
            name='playlisttrack',
            options={'ordering': ['order'], 'verbose_name': 'ترک پلی لیست', 'verbose_name_plural': 'ترک های پلی لیست'},
        ),
    ]
