# Generated by Django 6.0.6 on 2026-06-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_alter_playlist_options_alter_playlisttrack_options'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='playlist',
            name='playlists_p_owner_i_ca1a31_idx',
        ),
        migrations.AddField(
            model_name='playlist',
            name='title_fa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title FA'),
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='owner',
        ),
    ]
