# Generated by Django 6.0.6 on 2026-06-30 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0004_remove_playlist_playlists_p_owner_i_ca1a31_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlisttrack',
            unique_together=set(),
        ),
    ]
