# Generated by Django 6.0.7 on 2026-08-04 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_album_album_type_alter_albumarchiveupload_progress'),
        ('playlists', '0005_alter_playlisttrack_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='album',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='synced_playlist', to='music.album', verbose_name='آلبوم متناظر'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='is_editorial',
            field=models.BooleanField(db_index=True, default=False, verbose_name='پلی\u200cلیست رسمی/ادیتوریال'),
        ),
    ]
