# Generated by Django 6.0.7 on 2026-08-04 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_album_album_type_alter_albumarchiveupload_progress'),
        ('playlists', '0006_playlist_album_playlist_is_editorial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['-created_at'], 'verbose_name': 'پلی\u200cلیست شخصی', 'verbose_name_plural': 'پلی\u200cلیست\u200cهای شخصی'},
        ),
        migrations.AddField(
            model_name='playlist',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='عمومی است؟'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synced_playlists', to='music.album', verbose_name='آلبوم ادیتوریال مرتبط'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='playlists/covers/', verbose_name='تصویر کاور'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='is_editorial',
            field=models.BooleanField(default=False, verbose_name='پلی\u200cلیست ادیتوریال است؟'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=280, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان پلی\u200cلیست'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='title_fa',
            field=models.CharField(blank=True, max_length=255, verbose_name='عنوان فارسی'),
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='playlists.playlist', verbose_name='پلی\u200cلیست')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='music.track', verbose_name='ترک')),
            ],
            options={
                'verbose_name': 'آیتم پلی\u200cلیست',
                'verbose_name_plural': 'آیتم\u200cهای پلی\u200cلیست',
                'ordering': ['order', '-created_at'],
                'unique_together': {('playlist', 'track')},
            },
        ),
        migrations.AlterField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(related_name='in_playlists', through='playlists.PlaylistItem', to='music.track', verbose_name='ترک\u200cها'),
        ),
    ]
