# Generated by Django 6.0.7 on 2026-08-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_album_album_type_alter_albumarchiveupload_progress'),
        ('playlists', '0007_alter_playlist_options_playlist_is_public_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='playlisttrack',
            name='playlists_p_playlis_c81fae_idx',
        ),
        migrations.RemoveConstraint(
            model_name='playlisttrack',
            name='unique_playlist_track',
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['-created_at'], 'verbose_name': 'پلی\u200cلیست', 'verbose_name_plural': 'پلی\u200cلیست\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='playlistitem',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'آیتم پلی\u200cلیست', 'verbose_name_plural': 'آیتم\u200cهای پلی\u200cلیست'},
        ),
        migrations.AlterField(
            model_name='playlist',
            name='is_editorial',
            field=models.BooleanField(default=False, verbose_name='پلی\u200cلیست ادیتوریال'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='عمومی'),
        ),
        migrations.AddIndex(
            model_name='playlistitem',
            index=models.Index(fields=['playlist', 'order'], name='playlists_p_playlis_11e03f_idx'),
        ),
        migrations.DeleteModel(
            name='PlaylistTrack',
        ),
    ]
