# Generated by Django 6.0.7 on 2026-08-05 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0008_remove_playlisttrack_playlists_p_playlis_c81fae_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='album',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='is_editorial',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='is_public',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
            preserve_default=False,
        ),
    ]
