services:
  db:
    image: postgres:15.8
    container_name: classicalmusic_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: classicalmusic_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: classicalmusic_backend
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  #frontend:
   # build: ./frontend
    #container_name: classicalmusic_frontend
    #restart: unless-stopped
    #volumes:
    # - ./frontend:/app
    #  - /app/node_modules
    #ports:
    #  - "3000:3000"
    #command: sh -c "if [ ! -f package.json ]; then echo 'Next.js not installed yet' && sleep infinity; else npm run dev; fi"

  nginx:
    build: ./nginx
    container_name: classicalmusic_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    #  - frontend

volumes:
  postgres_data:

