# Generated by Django 5.2.15 on 2026-06-04 13:55

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(default='https://dl.classicalmusicofficial.com/media/defualt/pro.png', upload_to='profile_images/', verbose_name='تصویر پروفایل')),
                ('joined_date', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('subscription_start_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ شروع اشتراک')),
                ('subscription_end_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پایان اشتراک')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل کاربران',
            },
        ),
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_url', models.URLField(blank=True)),
                ('spotify_url', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('long_bio', models.TextField(blank=True)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='music.artist')),
            ],
        ),
    ]
