# Generated by Django 5.2.14 on 2026-05-16 13:59

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(default='https://dl.classicalmusicofficial.com/media/defualt/pro.png', upload_to='profile_images/', verbose_name='تصویر پروفایل')),
                ('joined_date', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('subscription_start_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ شروع اشتراک')),
                ('subscription_end_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پایان اشتراک')),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='کد تایید')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='تایید شماره تلفن')),
                ('verification_code_created_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ایجاد کد تایید')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل کاربران',
            },
        ),
    ]
