# Generated by Django 4.2.16 on 2026-09-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='https://dl.classicalmusicofficial.com/media/defualt/pro.png', null=True, upload_to='profile_images/', verbose_name='تصویر پروفایل'),
        ),
    ]
