# Generated by Django 5.2.15 on 2026-06-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='spotify_url',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='website',
        ),
    ]
