# Generated by Django 5.2.15 on 2026-06-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_artistprofile_instagram_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='long_bio',
        ),
    ]
