# Generated by Django 5.2.15 on 2026-06-10 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_artistprofile_long_bio'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userprofile',
            name='profiles_us_subscri_6dea65_idx',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription_end_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription_start_date',
        ),
    ]
