# Generated by Django 6.0.6 on 2026-07-03 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0016_alter_album_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان ویدیو')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=300, unique=True, verbose_name='اسلاگ')),
                ('era', models.CharField(blank=True, choices=[('renaissance', 'رنسانس'), ('baroque', 'باروک'), ('classical', 'کلاسیک'), ('romantic', 'رمانتیک'), ('impressionism', 'امپرسیونیسم'), ('modern', 'مدرن'), ('contemporary', 'معاصر')], db_index=True, max_length=20, null=True, verbose_name='دوره زمانی')),
                ('recording_year', models.PositiveIntegerField(blank=True, help_text='مثال:2018', null=True, verbose_name='سال ضبط')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت زمان (ثانیه)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='videos/covers/', verbose_name='کاور ویدیو')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/raw/', verbose_name='فایل خام ویدیو')),
                ('hls_file', models.CharField(blank=True, help_text='مسیر فایل master.m3u8 که به صورت خودکار توسط سیستم پر می\u200cشود', max_length=500, null=True, verbose_name='مسیر استریم HLS')),
                ('status', models.CharField(choices=[('processing', 'در حال پردازش'), ('published', 'منتشر شده')], default='processing', max_length=20)),
                ('view_count', models.PositiveBigIntegerField(default=0, verbose_name='بازدید')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='لایک ها')),
                ('artists', models.ManyToManyField(blank=True, related_name='videos', to='music.artist', verbose_name='آرتیست\u200cهای ویدیو')),
            ],
            options={
                'verbose_name': 'ویدیو',
                'verbose_name_plural': 'ویدیوها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_seconds', models.PositiveIntegerField(default=0, help_text='ثانیه\u200cای که کاربر تماشا را متوقف کرده است.', verbose_name='ثانیه\u200cهای تماشاشده')),
                ('is_completed', models.BooleanField(default=False, help_text='آیا کاربر ویدیو را تا انتها دیده است؟', verbose_name='تکمیل شده')),
                ('last_watched_at', models.DateTimeField(auto_now=True, verbose_name='آخرین زمان تماشا')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_histories', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='videos.video', verbose_name='ویدیو')),
            ],
            options={
                'verbose_name': 'تاریخچه تماشای ویدیو',
                'verbose_name_plural': 'تاریخچه تماشای ویدیوها',
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['recording_year'], name='videos_vide_recordi_7d76ca_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['status'], name='videos_vide_status_107761_idx'),
        ),
        migrations.AddIndex(
            model_name='videohistory',
            index=models.Index(fields=['user', 'video'], name='videos_vide_user_id_5a163f_idx'),
        ),
        migrations.AddIndex(
            model_name='videohistory',
            index=models.Index(fields=['-last_watched_at'], name='videos_vide_last_wa_758649_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='videohistory',
            unique_together={('user', 'video')},
        ),
    ]
