# Generated by Django 6.0.7 on 2026-07-13 16:00

import apps.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.common.models.video_path, verbose_name='فایل خام ویدیو'),
        ),
    ]
