# Generated by Django 6.0.7 on 2026-07-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='era',
            field=models.CharField(blank=True, choices=[('renaissance', 'رنسانس'), ('baroque', 'باروک'), ('classical', 'کلاسیک'), ('romantic', 'رمانتیک'), ('impressionism', 'امپرسیونیسم'), ('modern', 'مدرن'), ('contemporary', 'معاصر'), ('medieval', 'قرون وسطی'), ('early_20th', 'اوایل قرن بیستم'), ('late_20th', 'اواخر قرن بیستم'), ('century_21st', 'قرن بیست و یکم')], db_index=True, max_length=20, null=True, verbose_name='دوره زمانی'),
        ),
    ]
