# Generated by Django 6.0.7 on 2026-08-05 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticket',
            name='contacts_ti_user_id_e3e111_idx',
        ),
        migrations.RenameField(
            model_name='ticketmessage',
            old_name='body',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='ticketmessage',
            name='attachment',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('support', 'پشتیبانی عمومی'), ('track_request', 'درخواست اثر')], default='support', max_length=20, verbose_name='نوع تیکت'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'منتظر پاسخ ادمین'), ('user_replied', 'پاسخ کاربر'), ('answered', 'پاسخ داده شد'), ('closed', 'بسته شده')], db_index=True, default='open', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='فرستنده'),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='category',
        ),
    ]
