version = 5.6.0
archive_dir = /etc/letsencrypt/archive/clmusic.ir
cert = /etc/letsencrypt/live/clmusic.ir/cert.pem
privkey = /etc/letsencrypt/live/clmusic.ir/privkey.pem
chain = /etc/letsencrypt/live/clmusic.ir/chain.pem
fullchain = /etc/letsencrypt/live/clmusic.ir/fullchain.pem
[renewalparams]
account = 0c6e0b0502c1cb1c32cb4d2199bd01be
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
