version = 5.6.0
archive_dir = /etc/letsencrypt/archive/clmusic.ir
cert = /etc/letsencrypt/live/clmusic.ir/cert.pem
privkey = /etc/letsencrypt/live/clmusic.ir/privkey.pem
chain = /etc/letsencrypt/live/clmusic.ir/chain.pem
fullchain = /etc/letsencrypt/live/clmusic.ir/fullchain.pem
[renewalparams]
account = 2bfdd61c68c2e2fcdeb8bd90cde6398b
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
clmusic.ir = /var/www/certbot
www.clmusic.ir = /var/www/certbot
