# Generated by Django 5.2.15 on 2026-06-04 13:55

import apps.music.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=255, verbose_name='نام آرتیست')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True, verbose_name='اسلاگ')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='ملیت/کشور')),
                ('artist_type', models.CharField(choices=[('person', 'شخص'), ('orchestra', 'ارکستر'), ('ensemble', 'گروه'), ('choir', 'کر'), ('other', 'سایر')], db_index=True, default='person', max_length=20, verbose_name='نوع آرتیست')),
                ('era', models.CharField(blank=True, choices=[('renaissance', 'رنسانس'), ('baroque', 'باروک'), ('classical', 'کلاسیک'), ('romantic', 'رمانتیک'), ('impressionism', 'امپرسیونیسم'), ('modern', 'مدرن'), ('contemporary', 'معاصر')], db_index=True, max_length=20, null=True, verbose_name='دوره زمانی')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.music.models.artist_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='عکس')),
                ('biography', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده'), ('archived', 'آرشیوشده')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت انتشار')),
            ],
            options={
                'verbose_name': 'آرتیست',
                'verbose_name_plural': 'آرتیست\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='عنوان آلبوم')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True, verbose_name='اسلاگ')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.music.models.album_cover_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='تصویر آلبوم')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده'), ('archived', 'آرشیوشده')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت انتشار')),
                ('composers', models.ManyToManyField(blank=True, related_name='composed_albums', to='music.artist', verbose_name='آهنگسازان')),
                ('conductors', models.ManyToManyField(blank=True, related_name='conducted_albums', to='music.artist', verbose_name='رهبران ارکستر')),
                ('orchestras', models.ManyToManyField(blank=True, limit_choices_to={'artist_type': 'orchestra'}, related_name='orchestral_albums', to='music.artist', verbose_name='ارکسترها')),
                ('soloists', models.ManyToManyField(blank=True, related_name='solo_albums', to='music.artist', verbose_name='نوازندگان/سولیست\u200cها')),
            ],
            options={
                'verbose_name': 'آلبوم',
                'verbose_name_plural': 'آلبوم\u200cها',
                'ordering': ['-release_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='اسم ترک')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True, verbose_name='اسلاگ')),
                ('audio_file', models.FileField(upload_to=apps.music.models.track_audio_path, validators=[django.core.validators.FileExtensionValidator(['mp3', 'm4a', 'aac', 'flac', 'wav', 'ogg'])], verbose_name='فایل صوتی')),
                ('cover_image', models.ImageField(blank=True, help_text='اختیاری - در صورت خالی بودن می\u200cتواند در فرانت\u200cاند از کاور آلبوم استفاده شود.', null=True, upload_to=apps.music.models.track_cover_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='کاور ترک')),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='برای محاسبه زمان کل آلبوم ضروری است.', null=True, verbose_name='مدت زمان (میلی\u200cثانیه)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('track_number', models.PositiveIntegerField(default=1, verbose_name='شماره ترک')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده'), ('archived', 'آرشیوشده')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت انتشار')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.album', verbose_name='آلبوم')),
                ('composer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='composed_tracks', to='music.artist', verbose_name='آهنگساز')),
                ('singer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sung_tracks', to='music.artist', verbose_name='خواننده')),
            ],
            options={
                'verbose_name': 'ترک',
                'verbose_name_plural': 'ترک\u200cها',
                'ordering': ['album', 'track_number'],
            },
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['release_date'], name='music_album_release_5ffcba_idx'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('album', 'track_number'), name='uniq_track_number_per_album'),
        ),
    ]
