# Generated by Django 5.2.15 on 2026-06-14 12:49

import apps.common.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام ژانر')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'ژانر',
                'verbose_name_plural': 'ژانرها',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='نام ساز')),
                ('slug', models.SlugField(allow_unicode=True, max_length=35, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'ساز',
                'verbose_name_plural': 'ساز ها',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('composer', models.CharField(blank=True, max_length=255, verbose_name='نام آهنگساز')),
                ('title', models.CharField(blank=True, default='untitled', max_length=300, verbose_name='عنوان آلبوم')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=300, unique=True, verbose_name='اسلاگ')),
                ('source_path', models.CharField(max_length=500, null=True, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.common.models.album_cover_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='تصویر آلبوم')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('conductor', models.CharField(blank=True, max_length=255, verbose_name='نام رهبر ارکستر')),
                ('orchestra', models.CharField(blank=True, max_length=255, verbose_name='نام ارکستر')),
                ('soloist', models.CharField(blank=True, max_length=255, verbose_name='نام نوازنده')),
                ('ensemble', models.CharField(blank=True, max_length=255, verbose_name='نام گروه موسیقی')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده'), ('archived', 'آرشیوشده')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت انتشار')),
            ],
            options={
                'verbose_name': 'آلبوم',
                'verbose_name_plural': 'آلبوم\u200cها',
                'ordering': ['-release_date', 'title'],
                'indexes': [models.Index(fields=['release_date'], name='music_album_release_5ffcba_idx'), models.Index(fields=['status'], name='music_album_status_eaf41b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlbumArchiveUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('archive_file', models.FileField(upload_to='protected/tmp/archives/')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'در صف انتظار'), ('extracting', 'در حال استخراج'), ('processing', 'در حال پردازش متادیتا و آپلود'), ('completed', 'تکمیل شده'), ('failed', 'خطا')], default='pending', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0, help_text='درصد پیشرفت از $0$ تا $100$')),
                ('error_log', models.TextField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_uploads', to='music.album')),
            ],
            options={
                'verbose_name': 'آپلود گروهی آلبوم',
                'verbose_name_plural': 'آپلودهای گروهی آلبوم',
            },
        ),
        migrations.CreateModel(
            name='AlbumZipExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='protected/exports/albums/zips/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('album', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zip_export', to='music.album')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=255, verbose_name='نام آرتیست')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True, verbose_name='اسلاگ')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='ملیت/کشور')),
                ('artist_type', models.CharField(choices=[('person', 'شخص'), ('orchestra', 'ارکستر'), ('ensemble', 'گروه'), ('choir', 'کر'), ('other', 'سایر')], db_index=True, default='person', max_length=20, verbose_name='نوع آرتیست')),
                ('era', models.CharField(blank=True, choices=[('renaissance', 'رنسانس'), ('baroque', 'باروک'), ('classical', 'کلاسیک'), ('romantic', 'رمانتیک'), ('impressionism', 'امپرسیونیسم'), ('modern', 'مدرن'), ('contemporary', 'معاصر')], db_index=True, max_length=20, null=True, verbose_name='دوره زمانی')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.common.models.artist_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='عکس')),
                ('biography', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('related_artists', models.ManyToManyField(blank=True, to='music.artist')),
            ],
            options={
                'verbose_name': 'آرتیست',
                'verbose_name_plural': 'آرتیست\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(blank=True, default='Untitled', max_length=300, verbose_name='عنوان ترک')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=300, unique=True, verbose_name='اسلاگ')),
                ('audio_file', models.FileField(max_length=500, upload_to=apps.common.models.track_audio_path, validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'flac'])], verbose_name='فایل صوتی')),
                ('cover_image', models.ImageField(blank=True, help_text='اگر سینگل ترک است، حتماً کاور آپلود شود. در صورت داشتن آلبوم، کاور آلبوم اولویت دارد.', null=True, upload_to=apps.common.models.track_cover_path, verbose_name='کاور اختصاصی ترک')),
                ('release_date', models.DateField(blank=True, help_text='مخصوص سینگل ترک\u200cها', null=True, verbose_name='تاریخ انتشار ترک')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت زمان (میلی\u200cثانیه)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('track_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='شماره ترک در آلبوم')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده'), ('archived', 'آرشیوشده')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت انتشار')),
                ('is_chosen', models.BooleanField(default=False, help_text='منتخب')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.album', verbose_name='آلبوم')),
                ('composer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='composed_tracks', to='music.artist', verbose_name='آهنگساز')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='music.genre', verbose_name='ژانر')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='music.instrument', verbose_name='ساز')),
                ('singer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sung_tracks', to='music.artist', verbose_name='خواننده')),
            ],
            options={
                'verbose_name': 'ترک',
                'verbose_name_plural': 'ترک\u200cها',
                'ordering': ['album', 'track_number'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('album__isnull', False), ('track_number__isnull', False)), fields=('album', 'track_number'), name='uniq_track_position_in_album')],
            },
        ),
    ]
