# Generated by Django 5.2.14 on 2026-06-02 16:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('sort_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='نام مرتب\u200cسازی')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True, verbose_name='اسلاگ')),
                ('artist_type', models.CharField(choices=[('person', 'شخص'), ('orchestra', 'ارکستر'), ('ensemble', 'گروه'), ('choir', 'کر'), ('other', 'سایر')], db_index=True, default='person', max_length=20, verbose_name='نوع آرتیست')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='کشور')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='تاریخ وفات')),
                ('short_bio', models.TextField(blank=True, verbose_name='بیو کوتاه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='music/artists/images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='تصویر')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='ویژه')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده'), ('archived', 'آرشیوشده')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت انتشار')),
            ],
            options={
                'verbose_name': 'آرتیست',
                'verbose_name_plural': 'آرتیست\u200cها',
                'ordering': ['sort_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'ژانر',
                'verbose_name_plural': 'ژانرها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='اسلاگ')),
                ('website', models.URLField(blank=True, verbose_name='وب\u200cسایت')),
            ],
            options={
                'verbose_name': 'لیبل',
                'verbose_name_plural': 'لیبل\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'نوع اثر',
                'verbose_name_plural': 'انواع اثر',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='ویژه')),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='composer_profile', to='music.artist', verbose_name='آرتیست')),
                ('era', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='composers', to='music.era', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'آهنگساز',
                'verbose_name_plural': 'آهنگسازان',
                'ordering': ['artist__sort_name', 'artist__name'],
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='artists', to='music.genre', verbose_name='ژانرها'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True, verbose_name='اسلاگ')),
                ('album_type', models.CharField(choices=[('album', 'آلبوم'), ('single', 'تک\u200cآهنگ'), ('ep', 'ای\u200cپی'), ('compilation', 'منتخب'), ('box_set', 'باکس ست')], db_index=True, default='album', max_length=20, verbose_name='نوع آلبوم')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='music/albums/covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='کاور')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('editorial_note', models.TextField(blank=True, verbose_name='یادداشت تحریریه')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='ویژه')),
                ('popularity', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='محبوبیت')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده'), ('archived', 'آرشیوشده')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت انتشار')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='music.label', verbose_name='لیبل')),
            ],
            options={
                'verbose_name': 'آلبوم',
                'verbose_name_plural': 'آلبوم\u200cها',
                'ordering': ['-release_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('full_title', models.CharField(blank=True, max_length=500, verbose_name='عنوان کامل')),
                ('normalized_title', models.CharField(blank=True, db_index=True, max_length=500, verbose_name='عنوان نرمال')),
                ('slug', models.SlugField(blank=True, max_length=550, unique=True, verbose_name='اسلاگ')),
                ('composition_year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000)], verbose_name='سال ساخت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='ویژه')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده'), ('archived', 'آرشیوشده')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت انتشار')),
                ('composer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='music.composer', verbose_name='آهنگساز')),
                ('era', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='music.era', verbose_name='دوره')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='music.genre', verbose_name='ژانر')),
                ('parent_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_works', to='music.work', verbose_name='اثر والد')),
                ('work_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='music.worktype', verbose_name='نوع اثر')),
            ],
            options={
                'verbose_name': 'اثر',
                'verbose_name_plural': 'آثار',
                'ordering': ['composer__artist__sort_name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('title_override', models.CharField(blank=True, max_length=300, verbose_name='عنوان جایگزین')),
                ('recording_type', models.CharField(choices=[('studio', 'استودیویی'), ('live', 'اجرای زنده'), ('other', 'سایر')], db_index=True, default='studio', max_length=20, verbose_name='نوع ضبط')),
                ('recording_date', models.DateField(blank=True, null=True, verbose_name='تاریخ ضبط')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('is_complete_work', models.BooleanField(db_index=True, default=True, verbose_name='اجرای کامل اثر')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='مدت زمان (ms)')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='ویژه')),
                ('popularity', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='محبوبیت')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده'), ('archived', 'آرشیوشده')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت انتشار')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to='music.label', verbose_name='لیبل')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recordings', to='music.work', verbose_name='اثر')),
            ],
            options={
                'verbose_name': 'ضبط',
                'verbose_name_plural': 'ضبط\u200cها',
                'ordering': ['-is_featured', '-release_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecordingCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('role', models.CharField(choices=[('composer', 'آهنگساز'), ('conductor', 'رهبر ارکستر'), ('soloist', 'سولیست'), ('orchestra', 'ارکستر'), ('ensemble', 'گروه'), ('choir', 'کر'), ('performer', 'اجراکننده'), ('arranger', 'تنظیم\u200cکننده'), ('producer', 'تهیه\u200cکننده')], db_index=True, max_length=20, verbose_name='نقش')),
                ('credit_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب')),
                ('is_primary', models.BooleanField(db_index=True, default=False, verbose_name='اصلی')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording_credits', to='music.artist', verbose_name='آرتیست')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='music.recording', verbose_name='ضبط')),
            ],
            options={
                'verbose_name': 'کردیت ضبط',
                'verbose_name_plural': 'کردیت\u200cهای ضبط',
                'ordering': ['recording', 'credit_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('recording', 'artist', 'role'), name='uniq_recording_artist_role')],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('title_override', models.CharField(blank=True, max_length=300, verbose_name='عنوان جایگزین')),
                ('disc_number', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='شماره دیسک')),
                ('track_number', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='شماره ترک')),
                ('sequence_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب کلی')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='مدت زمان (ms)')),
                ('audio_file', models.FileField(upload_to='music/tracks/audio/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'm4a', 'aac', 'flac', 'wav', 'ogg'])], verbose_name='فایل صوتی')),
                ('file_size_bytes', models.BigIntegerField(default=0, verbose_name='حجم فایل')),
                ('audio_bitrate_kbps', models.PositiveIntegerField(blank=True, null=True, verbose_name='بیت\u200cریت')),
                ('audio_sample_rate_hz', models.PositiveIntegerField(blank=True, null=True, verbose_name='نرخ نمونه\u200cبرداری')),
                ('audio_codec', models.CharField(blank=True, max_length=30, verbose_name='کدک')),
                ('is_premium', models.BooleanField(db_index=True, default=False, verbose_name='پریمیوم')),
                ('is_streamable', models.BooleanField(db_index=True, default=True, verbose_name='قابل پخش')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده'), ('archived', 'آرشیوشده')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت انتشار')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to='music.album', verbose_name='آلبوم')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to='music.recording', verbose_name='ضبط')),
            ],
            options={
                'verbose_name': 'ترک',
                'verbose_name_plural': 'ترک\u200cها',
                'ordering': ['album', 'disc_number', 'track_number', 'sequence_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('album', 'disc_number', 'track_number'), name='uniq_album_disc_track_number')],
            },
        ),
        migrations.CreateModel(
            name='WorkCatalogRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('number', models.CharField(max_length=100, verbose_name='شماره')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_refs', to='music.work', verbose_name='اثر')),
            ],
            options={
                'verbose_name': 'مرجع کاتالوگ اثر',
                'verbose_name_plural': 'مراجع کاتالوگ اثر',
                'ordering': ['number'],
                'constraints': [models.UniqueConstraint(fields=('work', 'number'), name='uniq_work_catalog_ref')],
            },
        ),
        migrations.AddConstraint(
            model_name='work',
            constraint=models.UniqueConstraint(fields=('composer', 'title'), name='uniq_work_title_per_composer'),
        ),
    ]
