# Generated by Django 5.2.15 on 2026-06-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='composers',
        ),
        migrations.RemoveField(
            model_name='album',
            name='conductors',
        ),
        migrations.RemoveField(
            model_name='album',
            name='orchestras',
        ),
        migrations.RemoveField(
            model_name='album',
            name='soloists',
        ),
        migrations.AddField(
            model_name='album',
            name='composer',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام آهنگساز'),
        ),
        migrations.AddField(
            model_name='album',
            name='conductor',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام رهبر ارکستر'),
        ),
        migrations.AddField(
            model_name='album',
            name='ensemble',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام گروه موسیقی'),
        ),
        migrations.AddField(
            model_name='album',
            name='orchestra',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام ارکستر'),
        ),
        migrations.AddField(
            model_name='album',
            name='soloist',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام نوازنده'),
        ),
    ]
