# Generated by Django 5.2.15 on 2026-06-04 14:34

import apps.music.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_album_composers_remove_album_conductors_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='track',
            name='uniq_track_number_per_album',
        ),
        migrations.AddField(
            model_name='track',
            name='instrument',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ساز'),
        ),
        migrations.AddField(
            model_name='track',
            name='release_date',
            field=models.DateField(blank=True, help_text='مخصوص سینگل ترک\u200cها', null=True, verbose_name='تاریخ انتشار ترک'),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.album', verbose_name='آلبوم'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(upload_to=apps.music.models.track_audio_path, validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'flac'])], verbose_name='فایل صوتی'),
        ),
        migrations.AlterField(
            model_name='track',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='اگر سینگل ترک است، حتماً کاور آپلود شود.', null=True, upload_to=apps.music.models.track_cover_path, verbose_name='کاور اختصاصی ترک'),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت زمان (میلی\u200cثانیه)'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=300, verbose_name='عنوان ترک'),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شماره ترک در آلبوم'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(condition=models.Q(('album__isnull', False), ('track_number__isnull', False)), fields=('album', 'track_number'), name='uniq_track_position_in_album'),
        ),
    ]
