# Generated by Django 6.0.6 on 2026-06-16 09:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_album_status_alter_track_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام لیبل')),
                ('slug', models.SlugField(allow_unicode=True, max_length=300, unique=True, verbose_name='اسلاگ')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='labels/logos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='لوگوی لیبل')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='کشور')),
                ('website', models.URLField(blank=True, verbose_name='وب\u200cسایت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'لیبل (ناشر)',
                'verbose_name_plural': 'لیبل\u200cها (ناشرین)',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='music.label', verbose_name='لیبل ناشر'),
        ),
        migrations.AddField(
            model_name='track',
            name='label',
            field=models.ForeignKey(blank=True, help_text='برای سینگل\u200cترک\u200cها یا در صورتی که لیبل ترک با آلبوم متفاوت است.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='music.label', verbose_name='لیبل ناشر'),
        ),
    ]
