# Generated by Django 6.0.6 on 2026-06-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_label_album_label_track_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['name'], 'verbose_name': 'لیبل (ناشر)', 'verbose_name_plural': 'لیبل\u200cها'},
        ),
    ]
