# Generated by Django 5.2.15 on 2026-06-07 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_track_uniq_track_number_per_album_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumZipUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('zip_file', models.FileField(upload_to='temp/album_zips/', verbose_name='فایل ZIP آلبوم')),
                ('status', models.CharField(choices=[('pending', 'در صف انتظار'), ('processing', 'در حال پردازش و استخراج'), ('uploading', 'در حال انتقال به هاست دانلود'), ('completed', 'تکمیل شده'), ('failed', 'خطا در پردازش')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='شناسه تسک Celery')),
                ('report_log', models.TextField(blank=True, help_text='گزارش موفقیت یا خطای فایل\u200cها', verbose_name='لاگ عملیات')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zip_uploads', to='music.album', verbose_name='آلبوم')),
            ],
            options={
                'verbose_name': 'آپلود گروهی (ZIP)',
                'verbose_name_plural': 'آپلودهای گروهی (ZIP)',
            },
        ),
        migrations.CreateModel(
            name='TempTrackUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='temp/tracks/', verbose_name='فایل صوتی')),
                ('is_processed', models.BooleanField(default=False, verbose_name='پردازش شده؟')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='شناسه تسک Celery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.album', verbose_name='آلبوم')),
            ],
            options={
                'verbose_name': 'فایل آپلودی موقت',
                'verbose_name_plural': 'فایل\u200cهای آپلودی موقت',
            },
        ),
    ]
