# Generated by Django 5.2.15 on 2026-06-07 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_albumzipupload_temptrackupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='status',
        ),
    ]
