# Generated by Django 6.0.6 on 2026-06-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_label_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='comments_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد کامنت'),
        ),
        migrations.AddField(
            model_name='album',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد لایک'),
        ),
        migrations.AddField(
            model_name='artist',
            name='followers_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد فالوور'),
        ),
        migrations.AddField(
            model_name='artist',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد لایک'),
        ),
        migrations.AddField(
            model_name='label',
            name='followers_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد فالوور'),
        ),
        migrations.AddField(
            model_name='label',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد لایک'),
        ),
        migrations.AddField(
            model_name='track',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد لایک'),
        ),
    ]
