# Generated by Django 6.0.6 on 2026-06-19 01:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_album_comments_count_album_likes_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='play_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='تعداد کل پخش'),
        ),
        migrations.CreateModel(
            name='PlayHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('last_played_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین زمان پخش')),
                ('play_count', models.PositiveIntegerField(default=1, verbose_name='تعداد پخش کاربر')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_history', to='music.track', verbose_name='ترک')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_history', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تاریخچه پخش',
                'verbose_name_plural': 'تاریخچه پخش\u200cها',
                'ordering': ['-last_played_at'],
                'indexes': [models.Index(fields=['user', '-last_played_at'], name='music_playh_user_id_a26d19_idx')],
                'unique_together': {('user', 'track')},
            },
        ),
    ]
