# Generated by Django 5.2.15 on 2026-06-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_remove_artist_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albumzipupload',
            options={'verbose_name': 'آپلود گروهی', 'verbose_name_plural': 'آپلودهای گروهی'},
        ),
        migrations.RemoveField(
            model_name='albumzipupload',
            name='report_log',
        ),
        migrations.RemoveField(
            model_name='albumzipupload',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='albumzipupload',
            name='error_log',
            field=models.TextField(blank=True, null=True, verbose_name='لاگ خطا'),
        ),
        migrations.AddField(
            model_name='albumzipupload',
            name='progress',
            field=models.PositiveIntegerField(default=0, verbose_name='درصد پیشرفت'),
        ),
        migrations.AlterField(
            model_name='albumzipupload',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='albumzipupload',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در صف انتظار'), ('EXTRACTING', 'در حال استخراج فایل فشرده'), ('PROCESSING', 'در حال پردازش و استخراج متادیتا'), ('UPLOADING', 'در حال انتقال به هاست دانلود'), ('COMPLETED', 'تکمیل شده'), ('FAILED', 'خطا در پردازش')], default='PENDING', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='albumzipupload',
            name='zip_file',
            field=models.FileField(upload_to='temp_zips/', verbose_name='فایل فشرده (ZIP/RAR)'),
        ),
    ]
