# Generated by Django 5.2.15 on 2026-06-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_albumzipupload_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده'), ('archived', 'آرشیوشده')], db_index=True, default='published', max_length=20, verbose_name='وضعیت انتشار'),
        ),
        migrations.AlterField(
            model_name='track',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده'), ('archived', 'آرشیوشده')], db_index=True, default='published', max_length=20, verbose_name='وضعیت انتشار'),
        ),
    ]
