# Generated by Django 6.0.6 on 2026-06-19 13:36

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_track_play_count_playhistory'),
    ]

    operations = [
        TrigramExtension(),
    ]
