# Generated by Django 6.0.6 on 2026-06-19 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20260619_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='artists', to='music.album'),
        ),
        migrations.AlterField(
            model_name='album',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums_by_label', to='music.label', verbose_name='لیبل ناشر'),
        ),
    ]
