# Generated by Django 5.2.15 on 2026-06-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_album_status_alter_track_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumzipupload',
            name='processed_files',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='albumzipupload',
            name='total_files',
            field=models.IntegerField(default=0),
        ),
    ]
