# Generated by Django 6.0.6 on 2026-06-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_artist_albums_alter_album_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='source_path',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
