# Generated by Django 6.0.6 on 2026-06-20 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_artist_albums_alter_album_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='albums',
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='music.artist', verbose_name='آرتیست'),
        ),
        migrations.AlterField(
            model_name='album',
            name='source_path',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),

    ]
