# Generated by Django 5.2.15 on 2026-06-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_albumzipupload_processed_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='source_path',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
    ]
