# Generated by Django 5.2.15 on 2026-06-07 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_album_source_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temptrackupload',
            name='album',
        ),
        migrations.CreateModel(
            name='AlbumArchiveUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('archive_file', models.FileField(upload_to='tmp/archives/')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'در صف انتظار'), ('extracting', 'در حال استخراج'), ('processing', 'در حال پردازش متادیتا و آپلود'), ('completed', 'تکمیل شده'), ('failed', 'خطا')], default='pending', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0, help_text='درصد پیشرفت از $0$ تا $100$')),
                ('error_log', models.TextField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_uploads', to='music.album')),
            ],
            options={
                'verbose_name': 'آپلود گروهی آلبوم',
                'verbose_name_plural': 'آپلودهای گروهی آلبوم',
            },
        ),
        migrations.DeleteModel(
            name='AlbumZipUpload',
        ),
        migrations.DeleteModel(
            name='TempTrackUpload',
        ),
    ]
