# Generated by Django 6.0.6 on 2026-06-20 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_alter_album_source_path'),
        ('music', '0009_remove_artist_albums_album_artist_and_more'),
    ]

    operations = [
    ]
