# Generated by Django 5.2.15 on 2026-06-08 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_remove_temptrackupload_album_albumarchiveupload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumZipExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='exports/albums/zips/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('album', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zip_export', to='music.album')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
