# Generated by Django 6.0.6 on 2026-06-22 22:08

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_merge_20260621_0207'),
    ]

    operations = [
        TrigramExtension(),
    ]
