# Generated by Django 5.2.15 on 2026-06-10 13:13

import apps.music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_albumzipexport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='اگر سینگل ترک است، حتماً کاور آپلود شود. در صورت داشتن آلبوم، کاور آلبوم اولویت دارد.', null=True, upload_to=apps.music.models.track_cover_path, verbose_name='کاور اختصاصی ترک'),
        ),
    ]
