# Generated by Django 6.0.6 on 2026-06-23 12:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_enable_trigram_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumzipexport',
            name='download_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='albumzipexport',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
