# Generated by Django 5.2.15 on 2026-06-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_alter_track_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=300, unique=True, verbose_name='اسلاگ'),
        ),
    ]
