# Generated by Django 6.0.6 on 2026-06-23 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_albumzipexport_download_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumzipexport',
            name='error_log',
        ),
        migrations.RemoveField(
            model_name='albumzipexport',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='albumzipexport',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='albumzipexport',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zip_exports', to='music.album'),
        ),
        migrations.AlterField(
            model_name='albumzipexport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='albumzipexport',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='albumzipexport',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='album_zips/'),
        ),
    ]
