# Generated by Django 5.2.15 on 2026-06-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_alter_track_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='genre',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='زانر'),
        ),
    ]
