# Generated by Django 6.0.6 on 2026-06-23 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_remove_albumzipexport_error_log_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumzipexport',
            name='download_token',
        ),
        migrations.RemoveField(
            model_name='albumzipexport',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='albumzipexport',
            name='is_downloaded',
        ),
    ]
