# Generated by Django 5.2.15 on 2026-06-10 22:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_track_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام ژانر')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'ژانر',
                'verbose_name_plural': 'ژانرها',
            },
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(blank=True, default='untitled', max_length=300, verbose_name='عنوان آلبوم'),
        ),
        migrations.AlterField(
            model_name='albumarchiveupload',
            name='archive_file',
            field=models.FileField(upload_to='protected/tmp/archives/'),
        ),
        migrations.AlterField(
            model_name='albumzipexport',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='protected/exports/albums/zips/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(upload_to='protected/tracks/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'flac'])], verbose_name='فایل صوتی'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['status'], name='music_album_status_eaf41b_idx'),
        ),
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='music.genre', verbose_name='ژانر'),
        ),
    ]
