# Generated by Django 6.0.6 on 2026-06-28 16:54

import apps.common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_remove_albumzipexport_download_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='composer',
        ),
        migrations.RemoveField(
            model_name='album',
            name='conductor',
        ),
        migrations.RemoveField(
            model_name='album',
            name='ensemble',
        ),
        migrations.RemoveField(
            model_name='album',
            name='orchestra',
        ),
        migrations.RemoveField(
            model_name='album',
            name='soloist',
        ),
        migrations.RemoveField(
            model_name='track',
            name='composer',
        ),
        migrations.RemoveField(
            model_name='track',
            name='singer',
        ),
        migrations.AddField(
            model_name='album',
            name='title_fa',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='عنوان فارسی'),
        ),
        migrations.AddField(
            model_name='track',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='participated_tracks', to='music.artist', verbose_name='آرتیست\u200cهای مشارکت\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='music.artist', verbose_name='آرتیست اصلی'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_type',
            field=models.CharField(choices=[('composer', 'آهنگساز'), ('conductor', 'رهبر ارکستر'), ('orchestra', 'ارکستر'), ('soloist', 'نوازنده (سولیست)'), ('ensemble', 'گروه موسیقی'), ('singer', 'خواننده'), ('other', 'سایر')], db_index=True, default='other', max_length=20, verbose_name='نوع آرتیست'),
        ),
        migrations.AlterField(
            model_name='track',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.models.track_cover_path, verbose_name='کاور اختصاصی ترک'),
        ),
        migrations.AlterField(
            model_name='track',
            name='is_chosen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='track',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='music.label', verbose_name='لیبل ناشر'),
        ),
        migrations.AlterField(
            model_name='track',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ انتشار ترک'),
        ),
        migrations.CreateModel(
            name='AlbumCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('role', models.CharField(choices=[('composer', 'آهنگساز'), ('conductor', 'رهبر ارکستر'), ('orchestra', 'ارکستر'), ('soloist', 'نوازنده (سولیست)'), ('ensemble', 'گروه موسیقی'), ('singer', 'خواننده'), ('other', 'سایر')], max_length=50, verbose_name='نقش')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='music.album', verbose_name='آلبوم')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_credits', to='music.artist', verbose_name='آرتیست')),
            ],
            options={
                'verbose_name': 'عوامل آلبوم',
                'verbose_name_plural': 'عوامل آلبوم',
                'unique_together': {('album', 'artist', 'role')},
            },
        ),
    ]
