# Generated by Django 6.0.6 on 2026-06-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_remove_album_composer_remove_album_conductor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-release_year', 'title'], 'verbose_name': 'آلبوم', 'verbose_name_plural': 'آلبوم\u200cها'},
        ),
        migrations.RemoveIndex(
            model_name='album',
            name='music_album_release_5ffcba_idx',
        ),
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات نهایی آلبوم'),
        ),
        migrations.AddField(
            model_name='album',
            name='main_artists',
            field=models.ManyToManyField(blank=True, related_name='main_albums', to='music.artist', verbose_name='آرتیست\u200cهای اصلی'),
        ),
        migrations.AddField(
            model_name='album',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='سال انتشار'),
        ),
        migrations.AddField(
            model_name='artist',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, help_text='مثال:1958', null=True, verbose_name='سال تولد'),
        ),
        migrations.AddField(
            model_name='artist',
            name='death_year',
            field=models.PositiveIntegerField(blank=True, help_text='اگر زنده هستش ، این فیلد رو خالی بگذارید', null=True, verbose_name='سال فوت'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['release_year'], name='music_album_release_ee71e7_idx'),
        ),
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='album',
            name='release_date',
        ),
    ]
