# Generated by Django 5.2.15 on 2026-06-10 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_genre_alter_album_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.ForeignKey(blank=True, default='null', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='music.genre', verbose_name='ژانر'),
        ),
    ]
