# Generated by Django 6.0.7 on 2026-07-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_alter_album_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='nickname',
            field=models.CharField(blank=True, help_text='در صورت نداشتن نام مستعار، خالی بگذارید', max_length=255, null=True, verbose_name='نام مستعار'),
        ),
        migrations.AlterField(
            model_name='albumcredit',
            name='role',
            field=models.CharField(choices=[('composer', 'آهنگساز'), ('conductor', 'رهبر ارکستر'), ('orchestra', 'ارکستر'), ('soloist', 'سولیست'), ('ensemble', 'گروه موسیقی'), ('singer', 'خواننده'), ('pianist', 'پیانو'), ('organist', 'ارگ'), ('harpsichordist', 'هارپسیکورد'), ('cellist', 'ویولنسل'), ('violinist', 'ویولن'), ('violist', 'ویولا'), ('viola_da_gamba', 'ویولا دا گامبا'), ('guitarist', 'گیتار'), ('lutenist', 'لوت'), ('double_bassist', 'کنتر باس'), ('harpist', 'هارپ'), ('trumpeter', 'ترومپت'), ('horn', 'کُر'), ('trombonist', 'ترومبون'), ('tuba', 'توبا'), ('clarinetist', 'کلارینت'), ('oboist', 'اُبوا'), ('flutist', 'فلوت'), ('bassoonist', 'فاگوت (باسون)'), ('recorder', 'فلوت ریکوردر'), ('saxophonist', 'ساکسیفون'), ('accordionist', 'آکوردئون'), ('percussionist', 'پرکاشن'), ('soprano', 'سوپرانو'), ('mezzo_soprano', 'متزو سوپرانو'), ('countertenor', 'کانتر تنور'), ('tenor', 'تنور'), ('bass_baritone', 'باس باریتون'), ('other', 'سایر')], max_length=50, verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_type',
            field=models.CharField(choices=[('composer', 'آهنگساز'), ('conductor', 'رهبر ارکستر'), ('orchestra', 'ارکستر'), ('soloist', 'سولیست'), ('ensemble', 'گروه موسیقی'), ('singer', 'خواننده'), ('pianist', 'پیانو'), ('organist', 'ارگ'), ('harpsichordist', 'هارپسیکورد'), ('cellist', 'ویولنسل'), ('violinist', 'ویولن'), ('violist', 'ویولا'), ('viola_da_gamba', 'ویولا دا گامبا'), ('guitarist', 'گیتار'), ('lutenist', 'لوت'), ('double_bassist', 'کنتر باس'), ('harpist', 'هارپ'), ('trumpeter', 'ترومپت'), ('horn', 'کُر'), ('trombonist', 'ترومبون'), ('tuba', 'توبا'), ('clarinetist', 'کلارینت'), ('oboist', 'اُبوا'), ('flutist', 'فلوت'), ('bassoonist', 'فاگوت (باسون)'), ('recorder', 'فلوت ریکوردر'), ('saxophonist', 'ساکسیفون'), ('accordionist', 'آکوردئون'), ('percussionist', 'پرکاشن'), ('soprano', 'سوپرانو'), ('mezzo_soprano', 'متزو سوپرانو'), ('countertenor', 'کانتر تنور'), ('tenor', 'تنور'), ('bass_baritone', 'باس باریتون'), ('other', 'سایر')], db_index=True, default='other', max_length=20, verbose_name='نوع آرتیست'),
        ),
    ]
