# Generated by Django 5.2.15 on 2026-06-10 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_alter_track_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
    ]
