# Generated by Django 5.2.15 on 2026-06-10 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_remove_genre_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='نام ساز')),
                ('slug', models.SlugField(allow_unicode=True, max_length=35, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'ساز',
                'verbose_name_plural': 'ساز ها',
            },
        ),
        migrations.AlterField(
            model_name='track',
            name='instrument',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='music.instrument', verbose_name='ساز'),
        ),
    ]
