# Generated by Django 5.2.15 on 2026-06-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_instrument_alter_track_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(blank=True, default='Untitled', max_length=300, verbose_name='عنوان ترک'),
        ),
    ]
