# Generated by Django 6.0.7 on 2026-08-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_alter_artist_era'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_type',
            field=models.CharField(choices=[('official', 'آلبوم رسمی'), ('editorial_playlist', 'پلی\u200cلیست ادیتوریال')], db_index=True, default='official', max_length=20, verbose_name='نوع انتشار'),
        ),
        migrations.AlterField(
            model_name='albumarchiveupload',
            name='progress',
            field=models.PositiveIntegerField(default=0, help_text='درصد پیشرفت از 0 تا 100'),
        ),
    ]
