# Generated by Django 5.2.15 on 2026-06-11 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_alter_track_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='music.genre', verbose_name='ژانر'),
        ),
        migrations.AlterField(
            model_name='track',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='music.instrument', verbose_name='ساز'),
        ),
    ]
