# Generated by Django 4.2.16 on 2026-08-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_album_album_type_alter_albumarchiveupload_progress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['track_number'], 'verbose_name': 'ترک', 'verbose_name_plural': 'ترک ها'},
        ),
        migrations.RemoveConstraint(
            model_name='track',
            name='uniq_track_position_in_album',
        ),
        migrations.AlterField(
            model_name='albumzipexport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['album', 'track_number'], name='idx_track_album_num'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['status', 'created_at'], name='idx_track_status_created'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['genre', 'status'], name='idx_track_genre_status'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(condition=models.Q(('album__isnull', False)), fields=('album', 'track_number'), name='unique_track_number_per_album'),
        ),
    ]
