# Generated by Django 5.2.15 on 2026-06-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_alter_track_genre_alter_track_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=300, unique=True, verbose_name='اسلاگ'),
        ),
    ]
