# Generated by Django 4.2.16 on 2026-08-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_alter_track_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumzipexport',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
