# Generated by Django 4.2.16 on 2026-08-19 15:39

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_albumzipexport_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='album',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='idx_album_search_vector'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='idx_album_title_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='idx_artist_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nickname'], name='idx_artist_nick_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='label',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='idx_label_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='track',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='idx_track_search_vector'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='idx_track_title_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
