# Generated by Django 5.2.15 on 2026-06-11 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_alter_album_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(max_length=500, upload_to='protected/tracks/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'flac'])], verbose_name='فایل صوتی'),
        ),
    ]
