# Generated by Django 5.2.15 on 2026-06-11 22:03

import apps.common.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0022_alter_track_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده'), ('archived', 'آرشیوشده')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت انتشار'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(max_length=500, upload_to=apps.common.models.track_audio_path, validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'flac'])], verbose_name='فایل صوتی'),
        ),
        migrations.AlterField(
            model_name='track',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده'), ('archived', 'آرشیوشده')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت انتشار'),
        ),
    ]
