# Generated by Django 4.2.16 on 2026-08-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0024_add_title_fa_trgm_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='album',
            name='idx_album_title_fa_trgm',
        ),
        migrations.AlterField(
            model_name='track',
            name='is_chosen',
            field=models.BooleanField(default=False, verbose_name='منتخب؟'),
        ),
    ]
