# Generated by Django 4.2.16 on 2026-09-05 20:42

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0025_remove_album_idx_album_title_fa_trgm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumarchiveupload',
            name='archive_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='tmp/archives/'),
        ),
    ]
