# Generated by Django 4.2.16 on 2026-09-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0026_alter_albumarchiveupload_archive_file'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='track',
            name='unique_track_number_per_album',
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('album', 'track_number'), name='unique_track_number_per_album'),
        ),
    ]
