# Generated by Django 5.2.15 on 2026-06-14 12:49

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام اشتراک')),
                ('price', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='قیمت (تومان)')),
                ('duration_days', models.IntegerField(verbose_name='مدت زمان (روز)')),
                ('subscription_type', models.CharField(choices=[('online', 'فقط پخش آنلاین'), ('download', 'فقط دانلود'), ('videos', 'دانلود ویدیو ها'), ('both', 'دانلود و پخش'), ('all', 'همه قابلیت ها')], default='both', max_length=20, verbose_name='نوع اشتراک')),
                ('has_permanent_discount', models.BooleanField(default=False, verbose_name='تخفیف دائمی دارد')),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='قیمت با تخفیف')),
                ('discount_percentage', models.PositiveIntegerField(blank=True, help_text='به صورت خودکار محاسبه می\u200cشود', null=True, verbose_name='درصد تخفیف')),
                ('discount_label', models.CharField(blank=True, help_text='مثلاً: تخفیف ویژه، حراج نوروزی، ...', max_length=50, null=True, verbose_name='برچسب تخفیف')),
            ],
            options={
                'verbose_name': 'اشتراک',
                'verbose_name_plural': 'اشتراک\u200cها',
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='subscription_price_gte_0'), models.CheckConstraint(condition=models.Q(('duration_days__gt', 0)), name='subscription_duration_gt_0')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع')),
                ('end_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscription', verbose_name='اشتراک')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile', verbose_name='پروفایل کاربر')),
            ],
            options={
                'verbose_name': 'تاریخچه اشتراک',
                'verbose_name_plural': 'تاریخچه اشتراک\u200cها',
                'ordering': ['-start_date'],
            },
        ),
    ]
