# Generated by Django 5.2.15 on 2026-06-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='subscription_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('duration_days__gt', 0)), name='subscription_duration_gt_0'),
        ),
    ]
