# Generated by Django 5.2.15 on 2026-06-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_subscription_price_gte_0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='قیمت (تومان)'),
        ),
    ]
