# Generated by Django 5.2.15 on 2026-06-14 12:49

import django_jalali.db.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', unique=True, verbose_name='شماره موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('username', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='نام کاربری')),
                ('first_name', models.CharField(blank=True, max_length=20, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=20, verbose_name='نام خانوادگی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='کارمند')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='مدیر کل')),
                ('date_joined', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='آخرین ورود')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR')),
                ('code', models.CharField(max_length=6)),
                ('attempts', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.CharField(choices=[('LOGIN', 'LOGIN'), ('RESET_PASSWORD', 'RESET_PASSWORD'), ('REGISTER', 'REGISTER'), ('CHANGE_PHONE', 'CHANGE_PHONE')], db_index=True, default='LOGIN', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'purpose', '-created_at'], name='accounts_ot_phone_n_1600d0_idx')],
            },
        ),
    ]
