# Generated by Django 5.2.14 on 2026-05-11 18:56

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تخفیف')),
                ('code', models.CharField(help_text='کد منحصر به فرد تخفیف', max_length=20, unique=True, verbose_name='کد تخفیف')),
                ('description', models.TextField(help_text='توضیحات تخفیف', verbose_name='توضیحات')),
                ('discount_type', models.CharField(choices=[('percentage', 'درصدی'), ('fixed', 'مبلغ ثابت')], default='percentage', max_length=10, verbose_name='نوع تخفیف')),
                ('discount_value', models.DecimalField(decimal_places=0, help_text='در صورت درصدی: عدد بین 0 تا 100، در صورت مبلغ ثابت: مبلغ به تومان', max_digits=10, verbose_name='مقدار تخفیف')),
                ('discount_scope', models.CharField(choices=[('all', 'همه اشتراک\u200cها'), ('specific', 'اشتراک خاص'), ('category', 'دسته\u200cبندی خاص')], default='all', max_length=10, verbose_name='محدوده تخفیف')),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='0 برای نامحدود', verbose_name='حداکثر تعداد استفاده')),
                ('current_uses', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده شده')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, help_text='هر کاربر چند بار می\u200cتواند از این تخفیف استفاده کند', verbose_name='حداکثر استفاده هر کاربر')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع تخفیف')),
                ('end_date', django_jalali.db.models.jDateField(verbose_name='تاریخ پایان تخفیف')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام اشتراک')),
                ('price', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='قیمت')),
                ('duration_days', models.IntegerField(verbose_name='مدت زمان (روز)')),
                ('subscription_type', models.CharField(choices=[('online', 'فقط پخش آنلاین'), ('download', 'فقط دانلود'), ('both', 'دانلود و پخش')], default='both', max_length=20, verbose_name='نوع اشتراک')),
                ('has_permanent_discount', models.BooleanField(default=False, verbose_name='تخفیف دائمی دارد')),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='قیمت با تخفیف')),
                ('discount_percentage', models.PositiveIntegerField(blank=True, help_text='به صورت خودکار محاسبه می\u200cشود', null=True, verbose_name='درصد تخفیف')),
                ('discount_label', models.CharField(blank=True, help_text='مثلاً: تخفیف ویژه، حراج نوروزی، ...', max_length=50, null=True, verbose_name='برچسب تخفیف')),
            ],
            options={
                'verbose_name': 'اشتراک',
                'verbose_name_plural': 'اشتراک\u200cها',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید با 09 شروع شود و 11 رقم باشد', regex='^09[0-9]{9}$')], verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='نام کاربری')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='نام خانوادگی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='کارمند')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='مدیر کل')),
                ('date_joined', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='آخرین ورود')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', related_query_name='custom_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', related_query_name='custom_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت اصلی')),
                ('discounted_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت با تخفیف')),
                ('discount_amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مقدار تخفیف اعمال شده')),
                ('used_at', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ استفاده')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.discount', verbose_name='تخفیف')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser', verbose_name='کاربر')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subscription', verbose_name='اشتراک')),
            ],
            options={
                'verbose_name': 'استفاده از تخفیف',
                'verbose_name_plural': 'استفاده\u200cهای تخفیف',
                'ordering': ['-used_at'],
            },
        ),
        migrations.AddField(
            model_name='discount',
            name='applicable_subscriptions',
            field=models.ManyToManyField(blank=True, help_text="در صورت انتخاب 'اشتراک خاص' این فیلد الزامی است", to='accounts.subscription', verbose_name='اشتراک\u200cهای قابل اعمال'),
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع')),
                ('end_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subscription', verbose_name='اشتراک')),
            ],
            options={
                'verbose_name': 'تاریخچه اشتراک',
                'verbose_name_plural': 'تاریخچه اشتراک\u200cها',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(default='https://dl.classicalmusicofficial.com/media/defualt/pro.png', upload_to='profile_images/', verbose_name='تصویر پروفایل')),
                ('joined_date', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('subscription_start_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ شروع اشتراک')),
                ('subscription_end_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پایان اشتراک')),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='کد تایید')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='تایید شماره تلفن')),
                ('verification_code_created_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ایجاد کد تایید')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.subscription', verbose_name='اشتراک')),
                ('subscription_history', models.ManyToManyField(related_name='subscribers_history', through='accounts.SubscriptionHistory', to='accounts.subscription', verbose_name='تاریخچه اشتراک\u200cها')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل کاربران',
            },
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile', verbose_name='پروفایل کاربر'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['subscription_end_date'], name='accounts_us_subscri_991a56_idx'),
        ),
    ]
