# Generated by Django 6.0.6 on 2026-06-15 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='otpcode',
            name='accounts_ot_phone_n_1600d0_idx',
        ),
        migrations.DeleteModel(
            name='OTPCode',
        ),
    ]
