# Generated by Django 6.0.5 on 2026-05-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
