# Generated by Django 6.0.6 on 2026-06-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_otpcode_accounts_ot_phone_n_1600d0_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'احراز هویت کاربران'},
        ),
    ]
