# Generated by Django 6.0.6 on 2026-06-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_alter_comment_options_alter_follow_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'فالو', 'verbose_name_plural': 'فالویینگ ها'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'لایک', 'verbose_name_plural': 'لایک ها'},
        ),
    ]
