# Generated by Django 4.2.16 on 2026-08-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0006_remove_comment_album_comment_content_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'verbose_name': 'بوک\u200cمارک', 'verbose_name_plural': 'بوک\u200cمارک\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'فالو', 'verbose_name_plural': 'فالویینگ\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'لایک', 'verbose_name_plural': 'لایک\u200cها'},
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='unique_user_bookmark'),
        ),
    ]
