# Generated by Django 5.2.14 on 2026-05-16 13:59

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تخفیف')),
                ('code', models.CharField(help_text='کد منحصر به فرد تخفیف', max_length=20, unique=True, verbose_name='کد تخفیف')),
                ('description', models.TextField(help_text='توضیحات تخفیف', verbose_name='توضیحات')),
                ('discount_type', models.CharField(choices=[('percentage', 'درصدی'), ('fixed', 'مبلغ ثابت')], default='percentage', max_length=10, verbose_name='نوع تخفیف')),
                ('discount_value', models.DecimalField(decimal_places=0, help_text='در صورت درصدی: عدد بین 0 تا 100، در صورت مبلغ ثابت: مبلغ به تومان', max_digits=10, verbose_name='مقدار تخفیف')),
                ('discount_scope', models.CharField(choices=[('all', 'همه اشتراک\u200cها'), ('specific', 'اشتراک خاص'), ('category', 'دسته\u200cبندی خاص')], default='all', max_length=10, verbose_name='محدوده تخفیف')),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='0 برای نامحدود', verbose_name='حداکثر تعداد استفاده')),
                ('current_uses', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده شده')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, help_text='هر کاربر چند بار می\u200cتواند از این تخفیف استفاده کند', verbose_name='حداکثر استفاده هر کاربر')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع تخفیف')),
                ('end_date', django_jalali.db.models.jDateField(verbose_name='تاریخ پایان تخفیف')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت اصلی')),
                ('discounted_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت با تخفیف')),
                ('discount_amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مقدار تخفیف اعمال شده')),
                ('used_at', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ استفاده')),
            ],
            options={
                'verbose_name': 'استفاده از تخفیف',
                'verbose_name_plural': 'استفاده\u200cهای تخفیف',
                'ordering': ['-used_at'],
            },
        ),
    ]
