# Generated by Django 5.2.14 on 2026-05-16 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='applicable_subscriptions',
            field=models.ManyToManyField(blank=True, help_text="در صورت انتخاب 'اشتراک خاص' این فیلد الزامی است", to='subscriptions.subscription', verbose_name='اشتراک\u200cهای قابل اعمال'),
        ),
        migrations.AddField(
            model_name='discountusage',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.discount', verbose_name='تخفیف'),
        ),
        migrations.AddField(
            model_name='discountusage',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscription', verbose_name='اشتراک'),
        ),
        migrations.AddField(
            model_name='discountusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
