# Generated by Django 5.2.15 on 2026-06-14 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountusage',
            options={'verbose_name': 'استفاده از تخفیف', 'verbose_name_plural': 'استفاده\u200cهای تخفیف'},
        ),
        migrations.RemoveField(
            model_name='discountusage',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='discountusage',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='discountusage',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='discountusage',
            name='subscription',
        ),
        migrations.AlterField(
            model_name='discount',
            name='applicable_subscriptions',
            field=models.ManyToManyField(blank=True, to='subscriptions.subscription', verbose_name='اشتراک\u200cهای قابل اعمال'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='کد تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_scope',
            field=models.CharField(choices=[('all', 'همه اشتراک\u200cها'), ('specific', 'اشتراک خاص'), ('category', 'دسته\u200cبندی خاص')], default='all', max_length=20, verbose_name='محدوده تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'درصدی'), ('fixed', 'مبلغ ثابت')], default='percentage', max_length=20, verbose_name='نوع تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_value',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مقدار تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateTimeField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='max_uses',
            field=models.PositiveIntegerField(default=1, help_text='0 برای نامحدود', verbose_name='حداکثر استفاده کل'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='max_uses_per_user',
            field=models.PositiveIntegerField(default=1, verbose_name='حداکثر استفاده هر کاربر'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start_date',
            field=models.DateTimeField(verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='discountusage',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='payments.discount', verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='discountusage',
            name='used_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ استفاده'),
        ),
        migrations.AlterField(
            model_name='discountusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_usages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ پرداختی (تومان)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('success', 'موفقیت\u200cآمیز'), ('failed', 'ناموفق'), ('canceled', 'لغو شده توسط کاربر')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('authority', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='کد یکتای درگاه (Authority)')),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره پیگیری (RefID)')),
                ('card_pan', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره کارت ماسک شده')),
                ('gateway_data', models.JSONField(blank=True, default=dict, verbose_name='دیتای خام درگاه (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.discount', verbose_name='تخفیف اعمال شده')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscription', verbose_name='اشتراک')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تراکنش پرداخت',
                'verbose_name_plural': 'تراکنش\u200cهای پرداخت',
                'ordering': ['-created_at'],
            },
        ),
    ]
