# Generated by Django 6.0.6 on 2026-06-20 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_options_payment_card_pan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountusage',
            options={'verbose_name': 'استفاده از تخفیف', 'verbose_name_plural': 'تخفیف های استفاده شده'},
        ),
    ]
